env:
  global:
    - CC_TEST_REPORTER_ID=417fae3cad213c0c65cf89de32b6310b748a38c30651237eaf05303dd7f3ba15
sudo: false
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
before_install: gem install bundler -v 1.16.1
install: bundle install --path vendor/bundle
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake spec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
